### ISSUE TITLE
能不能跳过b站的版权限制

### ISSUE THREAD

**Issue by mountainguan** [tiansh/rbb#11]
通过使用bilibilijj的资源来实现海外播放b站正版视频

**Comment by tiansh** [comment]
这个脚本已经半停更不大可能去加什么新功能。而且这个功能听上去更像是那些海外看优酷的扩展应该解决的问题。

**Comment by mountainguan** [comment]
生活在ipv6的校园网内，如果用了unlock youku必须ipv4~

**Comment by tiansh** [comment]
理论上只要 `interface.bilibili.com/playurl` 过代理就可以，所以一个 xml 文件走 v4 应该影响不大。

**Comment by tiansh** [comment]
在 FoxyProxy 中，将 `http://interface.bilibili.com/playurl?*` 使用代理服务器（如 Unblock Youku 提供的服务器），即可正常找到播放器并播放。测试有效。而且走代理的网页因为很小，所以对网速基本没有影响。如果还有其它问题请重新打开这个问题并回复。

请注意在观看非版权番时，建议关闭该代理条目。
